### ISSUE TITLE
Cannot install new blocks

### ISSUE THREAD

**Issue by mdunbavan** [core77/foundation_sites#1]
Hi,

How can you install new blocks in the controller.php file.

I tried adding a block inside 'packages/foundation/blocks/test_block'

I then went into controller.php and amended it with:

```
private function installBlocks($pkg) {
        
        if (!BlockType::getByHandle('v_card')) {
            BlockType::installBlockTypeFromPackage('v_card', $pkg);
        }

        if (!BlockType::getByHandle('clearing_lightbox')) {
            BlockType::installBlockTypeFromPackage('clearing_lightbox', $pkg);
        }

        if (!BlockType::getByHandle('test_block')) {
            BlockType::installBlockTypeFromPackage('test_block', $pkg);
        }
}
```

I cannot see the block installed anywhere

**Comment by core77** [comment]
Hi. Did you also check the block's controller.php?

Assuming you did all right, you should see the block when you click on the +-sign, to add a block to a page.
